name: cyclops
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.48.0=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.0=h7b32b05_1
  - pip=25.0.1=pyh8b19718_0
  - python=3.9.18=h0755675_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.8.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.5.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - flatbuffers==25.2.10
      - gast==0.4.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - h5py==3.12.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - joblib==1.4.2
      - keras==2.13.1
      - keras-tuner==1.4.7
      - kt-legacy==1.0.5
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==3.0.2
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - rdkit==2023.9.5
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - typing-extensions==4.5.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zipp==3.21.0
prefix: /home/ciqus/anaconda3/envs/cyclops
